### ISSUE TITLE
Use Enums Rather than Strings to be type safe

### ISSUE THREAD

**Issue by Snazzie** [Azmekk/makeshift-RPG#1]
You should convert your classes to enum, then you can be type safe when consuming it.
See https://www.w3schools.com/cs/cs_enums.asp

https://github.com/Azmekk/makeshift-RPG/blob/ac9641f4abc4672471aa0432be3a43b96e82186d/Makeshift%20RPG/Characters/Class%20specifications.cs#L52

**Comment by Azmekk** [comment]
Resolved
